// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeAC-ZsjUtUnoU-J-IevXr0Tct2N3ynvU',
    appId: '1:965845248959:web:2fb8cb5e7183f82bddcf0a',
    messagingSenderId: '965845248959',
    projectId: 'pedrapp-6c089',
    authDomain: 'pedrapp-6c089.firebaseapp.com',
    storageBucket: 'pedrapp-6c089.firebasestorage.app',
    measurementId: 'G-HMNR21VDGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcyA8sjtoS0k83jEmKimYQ8g_O9-etanM',
    appId: '1:965845248959:android:f25054164a194dafddcf0a',
    messagingSenderId: '965845248959',
    projectId: 'pedrapp-6c089',
    storageBucket: 'pedrapp-6c089.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeAC-ZsjUtUnoU-J-IevXr0Tct2N3ynvU',
    appId: '1:965845248959:web:23a949ef083f5950ddcf0a',
    messagingSenderId: '965845248959',
    projectId: 'pedrapp-6c089',
    authDomain: 'pedrapp-6c089.firebaseapp.com',
    storageBucket: 'pedrapp-6c089.firebasestorage.app',
    measurementId: 'G-F94QJ93FN9',
  );
}
